spring:
  application:
    name: stock-manager-gateway
  cloud:
    gateway:
      routes:
        - id: product-get-service
          uri: ${CONSUMER_API_URI:http://localhost:8081}
          predicates:
            - Path=/products/**
            - Method=GET
        - id: product-others-service
          uri: ${PRODUCER_API_URI:http://localhost:8082}
          predicates:
            - Path=/products/**
            - Method=POST,PUT,DELETE
        - id: supplier-get-service
          uri: ${CONSUMER_API_URI:http://localhost:8081}
          predicates:
            - Path=/suppliers/**
            - Method=GET
        - id: supplier-others-service
          uri: ${PRODUCER_API_URI:http://localhost:8082}
          predicates:
            - Path=/supplier/**
            - Method=POST,PUT,DELETE
        - id: purchase-get-service
          uri: ${CONSUMER_API_URI:http://localhost:8081}
          predicates:
            - Path=/purchases/**
            - Method=GET
        - id: purchase-others-service
          uri: ${PRODUCER_API_URI:http://localhost:8082}
          predicates:
            - Path=/purchases/**
            - Method=POST,PUT,DELETE


